var tree = [["Thelia",,"",
                [["Condition","Thelia\/Condition.html","",
                [["Implementation","Thelia\/Condition\/Implementation.html","",
                [["MatchForEveryoneManager","Thelia\/Condition\/Implementation\/MatchForEveryoneManager.html"," < ConditionManagerAbstract",
                [        ]],["MatchForTotalAmountManager","Thelia\/Condition\/Implementation\/MatchForTotalAmountManager.html"," < ConditionManagerAbstract",
                [        ]],["MatchForXArticlesManager","Thelia\/Condition\/Implementation\/MatchForXArticlesManager.html"," < ConditionManagerAbstract",
                [        ]]        ]],["ConditionManagerAbstract","Thelia\/Condition\/ConditionManagerAbstract.html","",
                [        ]]        ]],["Controller",,"",
                [["Admin","Thelia\/Controller\/Admin.html","",
                [["AddressController","Thelia\/Controller\/Admin\/AddressController.html"," < AbstractCrudController",
                [        ]],["AdministratorController","Thelia\/Controller\/Admin\/AdministratorController.html"," < AbstractCrudController",
                [        ]],["AreaController","Thelia\/Controller\/Admin\/AreaController.html"," < AbstractCrudController",
                [        ]],["AttributeAvController","Thelia\/Controller\/Admin\/AttributeAvController.html"," < AbstractCrudController",
                [        ]],["AttributeController","Thelia\/Controller\/Admin\/AttributeController.html"," < AbstractCrudController",
                [        ]],["CategoryController","Thelia\/Controller\/Admin\/CategoryController.html"," < AbstractCrudController",
                [        ]],["ConfigController","Thelia\/Controller\/Admin\/ConfigController.html"," < AbstractCrudController",
                [        ]],["ContentController","Thelia\/Controller\/Admin\/ContentController.html"," < AbstractCrudController",
                [        ]],["CountryController","Thelia\/Controller\/Admin\/CountryController.html"," < AbstractCrudController",
                [        ]],["CurrencyController","Thelia\/Controller\/Admin\/CurrencyController.html"," < AbstractCrudController",
                [        ]],["FeatureAvController","Thelia\/Controller\/Admin\/FeatureAvController.html"," < AbstractCrudController",
                [        ]],["FeatureController","Thelia\/Controller\/Admin\/FeatureController.html"," < AbstractCrudController",
                [        ]],["FolderController","Thelia\/Controller\/Admin\/FolderController.html"," < AbstractCrudController",
                [        ]],["MessageController","Thelia\/Controller\/Admin\/MessageController.html"," < AbstractCrudController",
                [        ]],["ProductController","Thelia\/Controller\/Admin\/ProductController.html"," < AbstractCrudController",
                [        ]],["ProfileController","Thelia\/Controller\/Admin\/ProfileController.html"," < AbstractCrudController",
                [        ]],["TaxController","Thelia\/Controller\/Admin\/TaxController.html"," < AbstractCrudController",
                [        ]],["TaxRuleController","Thelia\/Controller\/Admin\/TaxRuleController.html"," < AbstractCrudController",
                [        ]],["TemplateController","Thelia\/Controller\/Admin\/TemplateController.html"," < AbstractCrudController",
                [        ]]        ]]        ]],["Core",,"",
                [["Event",,"",
                [["Area","Thelia\/Core\/Event\/Area.html","",
                [["AreaAddCountryEvent","Thelia\/Core\/Event\/Area\/AreaAddCountryEvent.html"," < AreaEvent",
                [        ]],["AreaDeleteEvent","Thelia\/Core\/Event\/Area\/AreaDeleteEvent.html"," < AreaEvent",
                [        ]],["AreaUpdatePostageEvent","Thelia\/Core\/Event\/Area\/AreaUpdatePostageEvent.html"," < AreaEvent",
                [        ]]        ]],["Attribute","Thelia\/Core\/Event\/Attribute.html","",
                [["AttributeAvDeleteEvent","Thelia\/Core\/Event\/Attribute\/AttributeAvDeleteEvent.html"," < AttributeAvEvent",
                [        ]],["AttributeDeleteEvent","Thelia\/Core\/Event\/Attribute\/AttributeDeleteEvent.html"," < AttributeEvent",
                [        ]]        ]],["Category","Thelia\/Core\/Event\/Category.html","",
                [["CategoryAddContentEvent","Thelia\/Core\/Event\/Category\/CategoryAddContentEvent.html"," < CategoryEvent",
                [        ]],["CategoryDeleteContentEvent","Thelia\/Core\/Event\/Category\/CategoryDeleteContentEvent.html"," < CategoryEvent",
                [        ]],["CategoryDeleteEvent","Thelia\/Core\/Event\/Category\/CategoryDeleteEvent.html"," < CategoryEvent",
                [        ]],["CategoryUpdateEvent","Thelia\/Core\/Event\/Category\/CategoryUpdateEvent.html"," < CategoryCreateEvent",
                [        ]]        ]],["Config","Thelia\/Core\/Event\/Config.html","",
                [["ConfigDeleteEvent","Thelia\/Core\/Event\/Config\/ConfigDeleteEvent.html"," < ConfigEvent",
                [        ]]        ]],["Content","Thelia\/Core\/Event\/Content.html","",
                [["ContentAddFolderEvent","Thelia\/Core\/Event\/Content\/ContentAddFolderEvent.html"," < ContentEvent",
                [        ]],["ContentDeleteEvent","Thelia\/Core\/Event\/Content\/ContentDeleteEvent.html"," < ContentEvent",
                [        ]]        ]],["Country","Thelia\/Core\/Event\/Country.html","",
                [["CountryDeleteEvent","Thelia\/Core\/Event\/Country\/CountryDeleteEvent.html"," < CountryEvent",
                [        ]],["CountryToggleDefaultEvent","Thelia\/Core\/Event\/Country\/CountryToggleDefaultEvent.html"," < CountryEvent",
                [        ]]        ]],["Currency","Thelia\/Core\/Event\/Currency.html","",
                [["CurrencyDeleteEvent","Thelia\/Core\/Event\/Currency\/CurrencyDeleteEvent.html"," < CurrencyEvent",
                [        ]]        ]],["Feature","Thelia\/Core\/Event\/Feature.html","",
                [["FeatureAvDeleteEvent","Thelia\/Core\/Event\/Feature\/FeatureAvDeleteEvent.html"," < FeatureAvEvent",
                [        ]],["FeatureDeleteEvent","Thelia\/Core\/Event\/Feature\/FeatureDeleteEvent.html"," < FeatureEvent",
                [        ]]        ]],["FeatureProduct","Thelia\/Core\/Event\/FeatureProduct.html","",
                [["FeatureProductDeleteEvent","Thelia\/Core\/Event\/FeatureProduct\/FeatureProductDeleteEvent.html"," < FeatureProductEvent",
                [        ]],["FeatureProductUpdateEvent","Thelia\/Core\/Event\/FeatureProduct\/FeatureProductUpdateEvent.html"," < FeatureProductEvent",
                [        ]]        ]],["Folder","Thelia\/Core\/Event\/Folder.html","",
                [["FolderDeleteEvent","Thelia\/Core\/Event\/Folder\/FolderDeleteEvent.html"," < FolderEvent",
                [        ]]        ]],["Lang","Thelia\/Core\/Event\/Lang.html","",
                [["LangDeleteEvent","Thelia\/Core\/Event\/Lang\/LangDeleteEvent.html"," < LangEvent",
                [        ]],["LangToggleDefaultEvent","Thelia\/Core\/Event\/Lang\/LangToggleDefaultEvent.html"," < LangEvent",
                [        ]]        ]],["Message","Thelia\/Core\/Event\/Message.html","",
                [["MessageDeleteEvent","Thelia\/Core\/Event\/Message\/MessageDeleteEvent.html"," < MessageEvent",
                [        ]]        ]],["Module","Thelia\/Core\/Event\/Module.html","",
                [["ModuleDeleteEvent","Thelia\/Core\/Event\/Module\/ModuleDeleteEvent.html"," < ModuleEvent",
                [        ]],["ModuleToggleActivationEvent","Thelia\/Core\/Event\/Module\/ModuleToggleActivationEvent.html"," < ModuleEvent",
                [        ]]        ]],["Product","Thelia\/Core\/Event\/Product.html","",
                [["ProductAddAccessoryEvent","Thelia\/Core\/Event\/Product\/ProductAddAccessoryEvent.html"," < ProductEvent",
                [        ]],["ProductAddCategoryEvent","Thelia\/Core\/Event\/Product\/ProductAddCategoryEvent.html"," < ProductEvent",
                [        ]],["ProductAddContentEvent","Thelia\/Core\/Event\/Product\/ProductAddContentEvent.html"," < ProductEvent",
                [        ]],["ProductCombinationGenerationEvent","Thelia\/Core\/Event\/Product\/ProductCombinationGenerationEvent.html"," < ProductEvent",
                [        ]],["ProductDeleteAccessoryEvent","Thelia\/Core\/Event\/Product\/ProductDeleteAccessoryEvent.html"," < ProductEvent",
                [        ]],["ProductDeleteCategoryEvent","Thelia\/Core\/Event\/Product\/ProductDeleteCategoryEvent.html"," < ProductEvent",
                [        ]],["ProductDeleteContentEvent","Thelia\/Core\/Event\/Product\/ProductDeleteContentEvent.html"," < ProductEvent",
                [        ]],["ProductDeleteEvent","Thelia\/Core\/Event\/Product\/ProductDeleteEvent.html"," < ProductEvent",
                [        ]],["ProductSetTemplateEvent","Thelia\/Core\/Event\/Product\/ProductSetTemplateEvent.html"," < ProductEvent",
                [        ]]        ]],["ProductSaleElement","Thelia\/Core\/Event\/ProductSaleElement.html","",
                [["ProductSaleElementCreateEvent","Thelia\/Core\/Event\/ProductSaleElement\/ProductSaleElementCreateEvent.html"," < ProductSaleElementEvent",
                [        ]],["ProductSaleElementDeleteEvent","Thelia\/Core\/Event\/ProductSaleElement\/ProductSaleElementDeleteEvent.html"," < ProductSaleElementEvent",
                [        ]],["ProductSaleElementUpdateEvent","Thelia\/Core\/Event\/ProductSaleElement\/ProductSaleElementUpdateEvent.html"," < ProductSaleElementEvent",
                [        ]]        ]],["Template","Thelia\/Core\/Event\/Template.html","",
                [["TemplateAddAttributeEvent","Thelia\/Core\/Event\/Template\/TemplateAddAttributeEvent.html"," < TemplateEvent",
                [        ]],["TemplateAddFeatureEvent","Thelia\/Core\/Event\/Template\/TemplateAddFeatureEvent.html"," < TemplateEvent",
                [        ]],["TemplateDeleteAttributeEvent","Thelia\/Core\/Event\/Template\/TemplateDeleteAttributeEvent.html"," < TemplateEvent",
                [        ]],["TemplateDeleteEvent","Thelia\/Core\/Event\/Template\/TemplateDeleteEvent.html"," < TemplateEvent",
                [        ]],["TemplateDeleteFeatureEvent","Thelia\/Core\/Event\/Template\/TemplateDeleteFeatureEvent.html"," < TemplateEvent",
                [        ]]        ]]        ]],["Security",,"",
                [["Authentication","Thelia\/Core\/Security\/Authentication.html","",
                [["AdminTokenAuthenticator","Thelia\/Core\/Security\/Authentication\/AdminTokenAuthenticator.html"," < TokenAuthenticator",
                [        ]],["AdminUsernamePasswordFormAuthenticator","Thelia\/Core\/Security\/Authentication\/AdminUsernamePasswordFormAuthenticator.html"," < UsernamePasswordFormAuthenticator",
                [        ]],["CustomerTokenAuthenticator","Thelia\/Core\/Security\/Authentication\/CustomerTokenAuthenticator.html"," < TokenAuthenticator",
                [        ]],["CustomerUsernamePasswordFormAuthenticator","Thelia\/Core\/Security\/Authentication\/CustomerUsernamePasswordFormAuthenticator.html"," < UsernamePasswordFormAuthenticator",
                [        ]],["TokenAuthenticator","Thelia\/Core\/Security\/Authentication\/TokenAuthenticator.html","",
                [        ]],["UsernamePasswordFormAuthenticator","Thelia\/Core\/Security\/Authentication\/UsernamePasswordFormAuthenticator.html","",
                [        ]]        ]],["Role","Thelia\/Core\/Security\/Role.html","",
                [["Role","Thelia\/Core\/Security\/Role\/Role.html","",
                [        ]]        ]],["UserProvider","Thelia\/Core\/Security\/UserProvider.html","",
                [["AdminTokenUserProvider","Thelia\/Core\/Security\/UserProvider\/AdminTokenUserProvider.html"," < TokenUserProvider",
                [        ]],["AdminUserProvider","Thelia\/Core\/Security\/UserProvider\/AdminUserProvider.html","",
                [        ]],["CustomerTokenUserProvider","Thelia\/Core\/Security\/UserProvider\/CustomerTokenUserProvider.html"," < TokenUserProvider",
                [        ]],["CustomerUserProvider","Thelia\/Core\/Security\/UserProvider\/CustomerUserProvider.html","",
                [        ]],["TokenUserProvider","Thelia\/Core\/Security\/UserProvider\/TokenUserProvider.html"," < TokenProvider",
                [        ]]        ]]        ]],["Template",,"",
                [["Loop","Thelia\/Core\/Template\/Loop.html","",
                [["Accessory","Thelia\/Core\/Template\/Loop\/Accessory.html"," < Product",
                [        ]],["Address","Thelia\/Core\/Template\/Loop\/Address.html"," < BaseLoop",
                [        ]],["Admin","Thelia\/Core\/Template\/Loop\/Admin.html"," < BaseLoop",
                [        ]],["Area","Thelia\/Core\/Template\/Loop\/Area.html"," < BaseLoop",
                [        ]],["AssociatedContent","Thelia\/Core\/Template\/Loop\/AssociatedContent.html"," < Content",
                [        ]],["Auth","Thelia\/Core\/Template\/Loop\/Auth.html"," < BaseLoop",
                [        ]],["Cart","Thelia\/Core\/Template\/Loop\/Cart.html"," < BaseLoop",
                [        ]],["Customer","Thelia\/Core\/Template\/Loop\/Customer.html"," < BaseLoop",
                [        ]],["Delivery","Thelia\/Core\/Template\/Loop\/Delivery.html"," < BaseSpecificModule",
                [        ]],["Feed","Thelia\/Core\/Template\/Loop\/Feed.html"," < BaseLoop",
                [        ]],["Lang","Thelia\/Core\/Template\/Loop\/Lang.html"," < BaseLoop",
                [        ]],["Order","Thelia\/Core\/Template\/Loop\/Order.html"," < BaseLoop",
                [        ]],["OrderAddress","Thelia\/Core\/Template\/Loop\/OrderAddress.html"," < BaseLoop",
                [        ]],["OrderProduct","Thelia\/Core\/Template\/Loop\/OrderProduct.html"," < BaseLoop",
                [        ]],["Payment","Thelia\/Core\/Template\/Loop\/Payment.html"," < BaseSpecificModule",
                [        ]],["Product","Thelia\/Core\/Template\/Loop\/Product.html"," < BaseI18nLoop",
                [        ]],["ProductSaleElements","Thelia\/Core\/Template\/Loop\/ProductSaleElements.html"," < BaseLoop",
                [        ]]        ]],["Smarty","Thelia\/Core\/Template\/Smarty.html","",
                [["Plugins","Thelia\/Core\/Template\/Smarty\/Plugins.html","",
                [["AdminUtilities","Thelia\/Core\/Template\/Smarty\/Plugins\/AdminUtilities.html"," < AbstractSmartyPlugin",
                [        ]],["Assetic","Thelia\/Core\/Template\/Smarty\/Plugins\/Assetic.html"," < AbstractSmartyPlugin",
                [        ]],["DataAccessFunctions","Thelia\/Core\/Template\/Smarty\/Plugins\/DataAccessFunctions.html"," < AbstractSmartyPlugin",
                [        ]],["FlashMessage","Thelia\/Core\/Template\/Smarty\/Plugins\/FlashMessage.html"," < AbstractSmartyPlugin",
                [        ]],["Form","Thelia\/Core\/Template\/Smarty\/Plugins\/Form.html"," < AbstractSmartyPlugin",
                [        ]],["Format","Thelia\/Core\/Template\/Smarty\/Plugins\/Format.html"," < AbstractSmartyPlugin",
                [        ]],["Module","Thelia\/Core\/Template\/Smarty\/Plugins\/Module.html"," < AbstractSmartyPlugin",
                [        ]],["Security","Thelia\/Core\/Template\/Smarty\/Plugins\/Security.html"," < AbstractSmartyPlugin",
                [        ]],["TheliaLoop","Thelia\/Core\/Template\/Smarty\/Plugins\/TheliaLoop.html"," < AbstractSmartyPlugin",
                [        ]],["TheliaSyntax","Thelia\/Core\/Template\/Smarty\/Plugins\/TheliaSyntax.html"," < AbstractSmartyPlugin",
                [        ]],["Translation","Thelia\/Core\/Template\/Smarty\/Plugins\/Translation.html"," < AbstractSmartyPlugin",
                [        ]],["Type","Thelia\/Core\/Template\/Smarty\/Plugins\/Type.html"," < AbstractSmartyPlugin",
                [        ]],["UrlGenerator","Thelia\/Core\/Template\/Smarty\/Plugins\/UrlGenerator.html"," < AbstractSmartyPlugin",
                [        ]]        ]],["SmartyParser","Thelia\/Core\/Template\/Smarty\/SmartyParser.html"," < Smarty",
                [        ]]        ]]        ]]        ]],["Coupon","Thelia\/Coupon.html","",
                [["Type","Thelia\/Coupon\/Type.html","",
                [["CouponAbstract","Thelia\/Coupon\/Type\/CouponAbstract.html","",
                [        ]],["RemoveXAmountManager","Thelia\/Coupon\/Type\/RemoveXAmountManager.html"," < CouponAbstract",
                [        ]],["RemoveXPercentManager","Thelia\/Coupon\/Type\/RemoveXPercentManager.html"," < CouponAbstract",
                [        ]]        ]],["BaseFacade","Thelia\/Coupon\/BaseFacade.html","",
                [        ]],["RuleOrganizer","Thelia\/Coupon\/RuleOrganizer.html","",
                [        ]]        ]],["Form","Thelia\/Form.html","",
                [["Area","Thelia\/Form\/Area.html","",
                [["AreaCountryForm","Thelia\/Form\/Area\/AreaCountryForm.html"," < BaseForm",
                [        ]],["AreaCreateForm","Thelia\/Form\/Area\/AreaCreateForm.html"," < BaseForm",
                [        ]],["AreaModificationForm","Thelia\/Form\/Area\/AreaModificationForm.html"," < AreaCreateForm",
                [        ]],["AreaPostageForm","Thelia\/Form\/Area\/AreaPostageForm.html"," < BaseForm",
                [        ]]        ]],["Lang","Thelia\/Form\/Lang.html","",
                [["LangCreateForm","Thelia\/Form\/Lang\/LangCreateForm.html"," < BaseForm",
                [        ]],["LangDefaultBehaviorForm","Thelia\/Form\/Lang\/LangDefaultBehaviorForm.html"," < BaseForm",
                [        ]],["LangUpdateForm","Thelia\/Form\/Lang\/LangUpdateForm.html"," < LangCreateForm",
                [        ]],["LangUrlForm","Thelia\/Form\/Lang\/LangUrlForm.html"," < BaseForm",
                [        ]]        ]],["ShippingZone","Thelia\/Form\/ShippingZone.html","",
                [["ShippingZoneAddArea","Thelia\/Form\/ShippingZone\/ShippingZoneAddArea.html"," < BaseForm",
                [        ]],["ShippingZoneRemoveArea","Thelia\/Form\/ShippingZone\/ShippingZoneRemoveArea.html"," < ShippingZoneAddArea",
                [        ]]        ]],["AddressCreateForm","Thelia\/Form\/AddressCreateForm.html"," < BaseForm",
                [        ]],["AddressUpdateForm","Thelia\/Form\/AddressUpdateForm.html"," < AddressCreateForm",
                [        ]],["AdminLogin","Thelia\/Form\/AdminLogin.html"," < BaseForm",
                [        ]],["AdministratorCreationForm","Thelia\/Form\/AdministratorCreationForm.html"," < BaseForm",
                [        ]],["AdministratorModificationForm","Thelia\/Form\/AdministratorModificationForm.html"," < AdministratorCreationForm",
                [        ]],["AttributeAvCreationForm","Thelia\/Form\/AttributeAvCreationForm.html"," < BaseForm",
                [        ]],["AttributeCreationForm","Thelia\/Form\/AttributeCreationForm.html"," < BaseForm",
                [        ]],["AttributeModificationForm","Thelia\/Form\/AttributeModificationForm.html"," < AttributeCreationForm",
                [        ]],["CartAdd","Thelia\/Form\/CartAdd.html"," < BaseForm",
                [        ]],["CategoryCreationForm","Thelia\/Form\/CategoryCreationForm.html"," < BaseForm",
                [        ]],["CategoryModificationForm","Thelia\/Form\/CategoryModificationForm.html"," < CategoryCreationForm",
                [        ]],["ConfigCreationForm","Thelia\/Form\/ConfigCreationForm.html"," < BaseForm",
                [        ]],["ConfigModificationForm","Thelia\/Form\/ConfigModificationForm.html"," < BaseForm",
                [        ]],["ContactForm","Thelia\/Form\/ContactForm.html"," < BaseForm",
                [        ]],["ContentCreationForm","Thelia\/Form\/ContentCreationForm.html"," < BaseForm",
                [        ]],["ContentModificationForm","Thelia\/Form\/ContentModificationForm.html"," < ContentCreationForm",
                [        ]],["CountryCreationForm","Thelia\/Form\/CountryCreationForm.html"," < BaseForm",
                [        ]],["CountryModificationForm","Thelia\/Form\/CountryModificationForm.html"," < CountryCreationForm",
                [        ]],["CouponCode","Thelia\/Form\/CouponCode.html"," < BaseForm",
                [        ]],["CouponCreationForm","Thelia\/Form\/CouponCreationForm.html"," < BaseForm",
                [        ]],["CurrencyCreationForm","Thelia\/Form\/CurrencyCreationForm.html"," < BaseForm",
                [        ]],["CurrencyModificationForm","Thelia\/Form\/CurrencyModificationForm.html"," < CurrencyCreationForm",
                [        ]],["CustomerCreateForm","Thelia\/Form\/CustomerCreateForm.html"," < AddressCreateForm",
                [        ]],["CustomerLogin","Thelia\/Form\/CustomerLogin.html"," < BaseForm",
                [        ]],["CustomerLostPasswordForm","Thelia\/Form\/CustomerLostPasswordForm.html"," < BaseForm",
                [        ]],["CustomerPasswordUpdateForm","Thelia\/Form\/CustomerPasswordUpdateForm.html"," < BaseForm",
                [        ]],["CustomerProfilUpdateForm","Thelia\/Form\/CustomerProfilUpdateForm.html"," < CustomerCreateForm",
                [        ]],["CustomerUpdateForm","Thelia\/Form\/CustomerUpdateForm.html"," < BaseForm",
                [        ]],["FeatureAvCreationForm","Thelia\/Form\/FeatureAvCreationForm.html"," < BaseForm",
                [        ]],["FeatureCreationForm","Thelia\/Form\/FeatureCreationForm.html"," < BaseForm",
                [        ]],["FeatureModificationForm","Thelia\/Form\/FeatureModificationForm.html"," < FeatureCreationForm",
                [        ]],["FolderCreationForm","Thelia\/Form\/FolderCreationForm.html"," < BaseForm",
                [        ]],["FolderModificationForm","Thelia\/Form\/FolderModificationForm.html"," < FolderCreationForm",
                [        ]],["InstallStep3Form","Thelia\/Form\/InstallStep3Form.html"," < BaseForm",
                [        ]],["MailingSystemModificationForm","Thelia\/Form\/MailingSystemModificationForm.html"," < BaseForm",
                [        ]],["MessageCreationForm","Thelia\/Form\/MessageCreationForm.html"," < BaseForm",
                [        ]],["MessageModificationForm","Thelia\/Form\/MessageModificationForm.html"," < BaseForm",
                [        ]],["NewsletterForm","Thelia\/Form\/NewsletterForm.html"," < BaseForm",
                [        ]],["OrderDelivery","Thelia\/Form\/OrderDelivery.html"," < BaseForm",
                [        ]],["OrderPayment","Thelia\/Form\/OrderPayment.html"," < BaseForm",
                [        ]],["OrderUpdateAddress","Thelia\/Form\/OrderUpdateAddress.html"," < BaseForm",
                [        ]],["ProductCombinationGenerationForm","Thelia\/Form\/ProductCombinationGenerationForm.html"," < BaseForm",
                [        ]],["ProductCreationForm","Thelia\/Form\/ProductCreationForm.html"," < BaseForm",
                [        ]],["ProductDefaultSaleElementUpdateForm","Thelia\/Form\/ProductDefaultSaleElementUpdateForm.html"," < ProductSaleElementUpdateForm",
                [        ]],["ProductModificationForm","Thelia\/Form\/ProductModificationForm.html"," < ProductCreationForm",
                [        ]],["ProductSaleElementUpdateForm","Thelia\/Form\/ProductSaleElementUpdateForm.html"," < BaseForm",
                [        ]],["ProfileCreationForm","Thelia\/Form\/ProfileCreationForm.html"," < BaseForm",
                [        ]],["ProfileModificationForm","Thelia\/Form\/ProfileModificationForm.html"," < ProfileCreationForm",
                [        ]],["ProfileUpdateModuleAccessForm","Thelia\/Form\/ProfileUpdateModuleAccessForm.html"," < BaseForm",
                [        ]],["ProfileUpdateResourceAccessForm","Thelia\/Form\/ProfileUpdateResourceAccessForm.html"," < BaseForm",
                [        ]],["SystemLogConfigurationForm","Thelia\/Form\/SystemLogConfigurationForm.html"," < BaseForm",
                [        ]],["TaxCreationForm","Thelia\/Form\/TaxCreationForm.html"," < BaseForm",
                [        ]],["TaxModificationForm","Thelia\/Form\/TaxModificationForm.html"," < TaxCreationForm",
                [        ]],["TaxRuleCreationForm","Thelia\/Form\/TaxRuleCreationForm.html"," < BaseForm",
                [        ]],["TaxRuleModificationForm","Thelia\/Form\/TaxRuleModificationForm.html"," < TaxRuleCreationForm",
                [        ]],["TaxRuleTaxListUpdateForm","Thelia\/Form\/TaxRuleTaxListUpdateForm.html"," < BaseForm",
                [        ]],["TemplateCreationForm","Thelia\/Form\/TemplateCreationForm.html"," < BaseForm",
                [        ]],["TemplateModificationForm","Thelia\/Form\/TemplateModificationForm.html"," < TemplateCreationForm",
                [        ]]        ]],["Install","Thelia\/Install.html","",
                [["CheckDatabaseConnection","Thelia\/Install\/CheckDatabaseConnection.html"," < BaseInstall",
                [        ]],["CheckPermission","Thelia\/Install\/CheckPermission.html"," < BaseInstall",
                [        ]]        ]],["Log",,"",
                [["Destination","Thelia\/Log\/Destination.html","",
                [["TlogDestinationFile","Thelia\/Log\/Destination\/TlogDestinationFile.html"," < AbstractTlogDestination",
                [        ]],["TlogDestinationHtml","Thelia\/Log\/Destination\/TlogDestinationHtml.html"," < AbstractTlogDestination",
                [        ]],["TlogDestinationJavascriptConsole","Thelia\/Log\/Destination\/TlogDestinationJavascriptConsole.html"," < AbstractTlogDestination",
                [        ]],["TlogDestinationNull","Thelia\/Log\/Destination\/TlogDestinationNull.html"," < AbstractTlogDestination",
                [        ]],["TlogDestinationPopup","Thelia\/Log\/Destination\/TlogDestinationPopup.html"," < AbstractTlogDestination",
                [        ]],["TlogDestinationText","Thelia\/Log\/Destination\/TlogDestinationText.html"," < AbstractTlogDestination",
                [        ]]        ]]        ]],["Model","Thelia\/Model.html","",
                [["Base","Thelia\/Model\/Base.html","",
                [["AccessoryQuery","Thelia\/Model\/Base\/AccessoryQuery.html"," < ModelCriteria",
                [        ]],["AddressQuery","Thelia\/Model\/Base\/AddressQuery.html"," < ModelCriteria",
                [        ]],["AdminLogQuery","Thelia\/Model\/Base\/AdminLogQuery.html"," < ModelCriteria",
                [        ]],["AdminQuery","Thelia\/Model\/Base\/AdminQuery.html"," < ModelCriteria",
                [        ]],["AreaDeliveryModuleQuery","Thelia\/Model\/Base\/AreaDeliveryModuleQuery.html"," < ModelCriteria",
                [        ]],["AreaQuery","Thelia\/Model\/Base\/AreaQuery.html"," < ModelCriteria",
                [        ]],["AttributeAvI18nQuery","Thelia\/Model\/Base\/AttributeAvI18nQuery.html"," < ModelCriteria",
                [        ]],["AttributeAvQuery","Thelia\/Model\/Base\/AttributeAvQuery.html"," < ModelCriteria",
                [        ]],["AttributeCombinationQuery","Thelia\/Model\/Base\/AttributeCombinationQuery.html"," < ModelCriteria",
                [        ]],["AttributeI18nQuery","Thelia\/Model\/Base\/AttributeI18nQuery.html"," < ModelCriteria",
                [        ]],["AttributeQuery","Thelia\/Model\/Base\/AttributeQuery.html"," < ModelCriteria",
                [        ]],["AttributeTemplateQuery","Thelia\/Model\/Base\/AttributeTemplateQuery.html"," < ModelCriteria",
                [        ]],["CartItemQuery","Thelia\/Model\/Base\/CartItemQuery.html"," < ModelCriteria",
                [        ]],["CartQuery","Thelia\/Model\/Base\/CartQuery.html"," < ModelCriteria",
                [        ]],["CategoryAssociatedContentQuery","Thelia\/Model\/Base\/CategoryAssociatedContentQuery.html"," < ModelCriteria",
                [        ]],["CategoryDocumentI18nQuery","Thelia\/Model\/Base\/CategoryDocumentI18nQuery.html"," < ModelCriteria",
                [        ]],["CategoryDocumentQuery","Thelia\/Model\/Base\/CategoryDocumentQuery.html"," < ModelCriteria",
                [        ]],["CategoryI18nQuery","Thelia\/Model\/Base\/CategoryI18nQuery.html"," < ModelCriteria",
                [        ]],["CategoryImageI18nQuery","Thelia\/Model\/Base\/CategoryImageI18nQuery.html"," < ModelCriteria",
                [        ]],["CategoryImageQuery","Thelia\/Model\/Base\/CategoryImageQuery.html"," < ModelCriteria",
                [        ]],["CategoryQuery","Thelia\/Model\/Base\/CategoryQuery.html"," < ModelCriteria",
                [        ]],["CategoryVersionQuery","Thelia\/Model\/Base\/CategoryVersionQuery.html"," < ModelCriteria",
                [        ]],["ConfigI18nQuery","Thelia\/Model\/Base\/ConfigI18nQuery.html"," < ModelCriteria",
                [        ]],["ConfigQuery","Thelia\/Model\/Base\/ConfigQuery.html"," < ModelCriteria",
                [        ]],["ContentDocumentI18nQuery","Thelia\/Model\/Base\/ContentDocumentI18nQuery.html"," < ModelCriteria",
                [        ]],["ContentDocumentQuery","Thelia\/Model\/Base\/ContentDocumentQuery.html"," < ModelCriteria",
                [        ]],["ContentFolderQuery","Thelia\/Model\/Base\/ContentFolderQuery.html"," < ModelCriteria",
                [        ]],["ContentI18nQuery","Thelia\/Model\/Base\/ContentI18nQuery.html"," < ModelCriteria",
                [        ]],["ContentImageI18nQuery","Thelia\/Model\/Base\/ContentImageI18nQuery.html"," < ModelCriteria",
                [        ]],["ContentImageQuery","Thelia\/Model\/Base\/ContentImageQuery.html"," < ModelCriteria",
                [        ]],["ContentQuery","Thelia\/Model\/Base\/ContentQuery.html"," < ModelCriteria",
                [        ]],["ContentVersionQuery","Thelia\/Model\/Base\/ContentVersionQuery.html"," < ModelCriteria",
                [        ]],["CountryI18nQuery","Thelia\/Model\/Base\/CountryI18nQuery.html"," < ModelCriteria",
                [        ]],["CountryQuery","Thelia\/Model\/Base\/CountryQuery.html"," < ModelCriteria",
                [        ]],["CouponI18nQuery","Thelia\/Model\/Base\/CouponI18nQuery.html"," < ModelCriteria",
                [        ]],["CouponOrderQuery","Thelia\/Model\/Base\/CouponOrderQuery.html"," < ModelCriteria",
                [        ]],["CouponQuery","Thelia\/Model\/Base\/CouponQuery.html"," < ModelCriteria",
                [        ]],["CouponVersionQuery","Thelia\/Model\/Base\/CouponVersionQuery.html"," < ModelCriteria",
                [        ]],["CurrencyI18nQuery","Thelia\/Model\/Base\/CurrencyI18nQuery.html"," < ModelCriteria",
                [        ]],["CurrencyQuery","Thelia\/Model\/Base\/CurrencyQuery.html"," < ModelCriteria",
                [        ]],["CustomerQuery","Thelia\/Model\/Base\/CustomerQuery.html"," < ModelCriteria",
                [        ]],["CustomerTitleI18nQuery","Thelia\/Model\/Base\/CustomerTitleI18nQuery.html"," < ModelCriteria",
                [        ]],["CustomerTitleQuery","Thelia\/Model\/Base\/CustomerTitleQuery.html"," < ModelCriteria",
                [        ]],["FeatureAvI18nQuery","Thelia\/Model\/Base\/FeatureAvI18nQuery.html"," < ModelCriteria",
                [        ]],["FeatureAvQuery","Thelia\/Model\/Base\/FeatureAvQuery.html"," < ModelCriteria",
                [        ]],["FeatureI18nQuery","Thelia\/Model\/Base\/FeatureI18nQuery.html"," < ModelCriteria",
                [        ]],["FeatureProductQuery","Thelia\/Model\/Base\/FeatureProductQuery.html"," < ModelCriteria",
                [        ]],["FeatureQuery","Thelia\/Model\/Base\/FeatureQuery.html"," < ModelCriteria",
                [        ]],["FeatureTemplateQuery","Thelia\/Model\/Base\/FeatureTemplateQuery.html"," < ModelCriteria",
                [        ]],["FolderDocumentI18nQuery","Thelia\/Model\/Base\/FolderDocumentI18nQuery.html"," < ModelCriteria",
                [        ]],["FolderDocumentQuery","Thelia\/Model\/Base\/FolderDocumentQuery.html"," < ModelCriteria",
                [        ]],["FolderI18nQuery","Thelia\/Model\/Base\/FolderI18nQuery.html"," < ModelCriteria",
                [        ]],["FolderImageI18nQuery","Thelia\/Model\/Base\/FolderImageI18nQuery.html"," < ModelCriteria",
                [        ]],["FolderImageQuery","Thelia\/Model\/Base\/FolderImageQuery.html"," < ModelCriteria",
                [        ]],["FolderQuery","Thelia\/Model\/Base\/FolderQuery.html"," < ModelCriteria",
                [        ]],["FolderVersionQuery","Thelia\/Model\/Base\/FolderVersionQuery.html"," < ModelCriteria",
                [        ]],["LangQuery","Thelia\/Model\/Base\/LangQuery.html"," < ModelCriteria",
                [        ]],["MessageI18nQuery","Thelia\/Model\/Base\/MessageI18nQuery.html"," < ModelCriteria",
                [        ]],["MessageQuery","Thelia\/Model\/Base\/MessageQuery.html"," < ModelCriteria",
                [        ]],["MessageVersionQuery","Thelia\/Model\/Base\/MessageVersionQuery.html"," < ModelCriteria",
                [        ]],["ModuleI18nQuery","Thelia\/Model\/Base\/ModuleI18nQuery.html"," < ModelCriteria",
                [        ]],["ModuleImageI18nQuery","Thelia\/Model\/Base\/ModuleImageI18nQuery.html"," < ModelCriteria",
                [        ]],["ModuleImageQuery","Thelia\/Model\/Base\/ModuleImageQuery.html"," < ModelCriteria",
                [        ]],["ModuleQuery","Thelia\/Model\/Base\/ModuleQuery.html"," < ModelCriteria",
                [        ]],["NewsletterQuery","Thelia\/Model\/Base\/NewsletterQuery.html"," < ModelCriteria",
                [        ]],["OrderAddressQuery","Thelia\/Model\/Base\/OrderAddressQuery.html"," < ModelCriteria",
                [        ]],["OrderFeatureQuery","Thelia\/Model\/Base\/OrderFeatureQuery.html"," < ModelCriteria",
                [        ]],["OrderProductAttributeCombinationQuery","Thelia\/Model\/Base\/OrderProductAttributeCombinationQuery.html"," < ModelCriteria",
                [        ]],["OrderProductQuery","Thelia\/Model\/Base\/OrderProductQuery.html"," < ModelCriteria",
                [        ]],["OrderProductTaxQuery","Thelia\/Model\/Base\/OrderProductTaxQuery.html"," < ModelCriteria",
                [        ]],["OrderQuery","Thelia\/Model\/Base\/OrderQuery.html"," < ModelCriteria",
                [        ]],["OrderStatusI18nQuery","Thelia\/Model\/Base\/OrderStatusI18nQuery.html"," < ModelCriteria",
                [        ]],["OrderStatusQuery","Thelia\/Model\/Base\/OrderStatusQuery.html"," < ModelCriteria",
                [        ]],["ProductAssociatedContentQuery","Thelia\/Model\/Base\/ProductAssociatedContentQuery.html"," < ModelCriteria",
                [        ]],["ProductCategoryQuery","Thelia\/Model\/Base\/ProductCategoryQuery.html"," < ModelCriteria",
                [        ]],["ProductDocumentI18nQuery","Thelia\/Model\/Base\/ProductDocumentI18nQuery.html"," < ModelCriteria",
                [        ]],["ProductDocumentQuery","Thelia\/Model\/Base\/ProductDocumentQuery.html"," < ModelCriteria",
                [        ]],["ProductI18nQuery","Thelia\/Model\/Base\/ProductI18nQuery.html"," < ModelCriteria",
                [        ]],["ProductImageI18nQuery","Thelia\/Model\/Base\/ProductImageI18nQuery.html"," < ModelCriteria",
                [        ]],["ProductImageQuery","Thelia\/Model\/Base\/ProductImageQuery.html"," < ModelCriteria",
                [        ]],["ProductPriceQuery","Thelia\/Model\/Base\/ProductPriceQuery.html"," < ModelCriteria",
                [        ]],["ProductQuery","Thelia\/Model\/Base\/ProductQuery.html"," < ModelCriteria",
                [        ]],["ProductSaleElementsQuery","Thelia\/Model\/Base\/ProductSaleElementsQuery.html"," < ModelCriteria",
                [        ]],["ProductVersionQuery","Thelia\/Model\/Base\/ProductVersionQuery.html"," < ModelCriteria",
                [        ]],["ProfileI18nQuery","Thelia\/Model\/Base\/ProfileI18nQuery.html"," < ModelCriteria",
                [        ]],["ProfileModuleQuery","Thelia\/Model\/Base\/ProfileModuleQuery.html"," < ModelCriteria",
                [        ]],["ProfileQuery","Thelia\/Model\/Base\/ProfileQuery.html"," < ModelCriteria",
                [        ]],["ProfileResourceQuery","Thelia\/Model\/Base\/ProfileResourceQuery.html"," < ModelCriteria",
                [        ]],["ResourceI18nQuery","Thelia\/Model\/Base\/ResourceI18nQuery.html"," < ModelCriteria",
                [        ]],["ResourceQuery","Thelia\/Model\/Base\/ResourceQuery.html"," < ModelCriteria",
                [        ]],["RewritingArgumentQuery","Thelia\/Model\/Base\/RewritingArgumentQuery.html"," < ModelCriteria",
                [        ]],["RewritingUrlQuery","Thelia\/Model\/Base\/RewritingUrlQuery.html"," < ModelCriteria",
                [        ]],["TaxI18nQuery","Thelia\/Model\/Base\/TaxI18nQuery.html"," < ModelCriteria",
                [        ]],["TaxQuery","Thelia\/Model\/Base\/TaxQuery.html"," < ModelCriteria",
                [        ]],["TaxRuleCountryQuery","Thelia\/Model\/Base\/TaxRuleCountryQuery.html"," < ModelCriteria",
                [        ]],["TaxRuleI18nQuery","Thelia\/Model\/Base\/TaxRuleI18nQuery.html"," < ModelCriteria",
                [        ]],["TaxRuleQuery","Thelia\/Model\/Base\/TaxRuleQuery.html"," < ModelCriteria",
                [        ]],["TemplateI18nQuery","Thelia\/Model\/Base\/TemplateI18nQuery.html"," < ModelCriteria",
                [        ]],["TemplateQuery","Thelia\/Model\/Base\/TemplateQuery.html"," < ModelCriteria",
                [        ]]        ]],["Accessory","Thelia\/Model\/Accessory.html"," < Accessory",
                [        ]],["Address","Thelia\/Model\/Address.html"," < Address",
                [        ]],["Admin","Thelia\/Model\/Admin.html"," < Admin",
                [        ]],["Area","Thelia\/Model\/Area.html"," < Area",
                [        ]],["Attribute","Thelia\/Model\/Attribute.html"," < Attribute",
                [        ]],["AttributeAv","Thelia\/Model\/AttributeAv.html"," < AttributeAv",
                [        ]],["AttributeTemplate","Thelia\/Model\/AttributeTemplate.html"," < AttributeTemplate",
                [        ]],["CartItem","Thelia\/Model\/CartItem.html"," < CartItem",
                [        ]],["Category","Thelia\/Model\/Category.html"," < Category",
                [        ]],["CategoryAssociatedContent","Thelia\/Model\/CategoryAssociatedContent.html"," < CategoryAssociatedContent",
                [        ]],["CategoryDocument","Thelia\/Model\/CategoryDocument.html"," < CategoryDocument",
                [        ]],["CategoryI18n","Thelia\/Model\/CategoryI18n.html"," < CategoryI18n",
                [        ]],["CategoryImage","Thelia\/Model\/CategoryImage.html"," < CategoryImage",
                [        ]],["Config","Thelia\/Model\/Config.html"," < Config",
                [        ]],["Content","Thelia\/Model\/Content.html"," < Content",
                [        ]],["ContentDocument","Thelia\/Model\/ContentDocument.html"," < ContentDocument",
                [        ]],["ContentI18n","Thelia\/Model\/ContentI18n.html"," < ContentI18n",
                [        ]],["ContentImage","Thelia\/Model\/ContentImage.html"," < ContentImage",
                [        ]],["Country","Thelia\/Model\/Country.html"," < Country",
                [        ]],["Currency","Thelia\/Model\/Currency.html"," < Currency",
                [        ]],["Customer","Thelia\/Model\/Customer.html"," < Customer",
                [        ]],["Feature","Thelia\/Model\/Feature.html"," < Feature",
                [        ]],["FeatureAv","Thelia\/Model\/FeatureAv.html"," < FeatureAv",
                [        ]],["FeatureProduct","Thelia\/Model\/FeatureProduct.html"," < FeatureProduct",
                [        ]],["FeatureTemplate","Thelia\/Model\/FeatureTemplate.html"," < FeatureTemplate",
                [        ]],["Folder","Thelia\/Model\/Folder.html"," < Folder",
                [        ]],["FolderDocument","Thelia\/Model\/FolderDocument.html"," < FolderDocument",
                [        ]],["FolderI18n","Thelia\/Model\/FolderI18n.html"," < FolderI18n",
                [        ]],["FolderImage","Thelia\/Model\/FolderImage.html"," < FolderImage",
                [        ]],["Lang","Thelia\/Model\/Lang.html"," < Lang",
                [        ]],["Message","Thelia\/Model\/Message.html"," < Message",
                [        ]],["Module","Thelia\/Model\/Module.html"," < Module",
                [        ]],["Order","Thelia\/Model\/Order.html"," < Order",
                [        ]],["OrderProduct","Thelia\/Model\/OrderProduct.html"," < OrderProduct",
                [        ]],["Product","Thelia\/Model\/Product.html"," < Product",
                [        ]],["ProductAssociatedContent","Thelia\/Model\/ProductAssociatedContent.html"," < ProductAssociatedContent",
                [        ]],["ProductDocument","Thelia\/Model\/ProductDocument.html"," < ProductDocument",
                [        ]],["ProductI18n","Thelia\/Model\/ProductI18n.html"," < ProductI18n",
                [        ]],["ProductImage","Thelia\/Model\/ProductImage.html"," < ProductImage",
                [        ]],["RewritingUrl","Thelia\/Model\/RewritingUrl.html"," < RewritingUrl",
                [        ]],["Template","Thelia\/Model\/Template.html"," < Template",
                [        ]]        ]],["TaxEngine",,"",
                [["TaxType","Thelia\/TaxEngine\/TaxType.html","",
                [["FeatureFixAmountTaxType","Thelia\/TaxEngine\/TaxType\/FeatureFixAmountTaxType.html"," < BaseTaxType",
                [        ]],["FixAmountTaxType","Thelia\/TaxEngine\/TaxType\/FixAmountTaxType.html"," < BaseTaxType",
                [        ]],["PricePercentTaxType","Thelia\/TaxEngine\/TaxType\/PricePercentTaxType.html"," < BaseTaxType",
                [        ]]        ]]        ]],["Type","Thelia\/Type.html","",
                [["AlphaNumStringListType","Thelia\/Type\/AlphaNumStringListType.html"," < BaseType",
                [        ]],["AlphaNumStringType","Thelia\/Type\/AlphaNumStringType.html"," < BaseType",
                [        ]],["AnyType","Thelia\/Type\/AnyType.html"," < BaseType",
                [        ]],["BaseType","Thelia\/Type\/BaseType.html","",
                [        ]],["BooleanOrBothType","Thelia\/Type\/BooleanOrBothType.html"," < BaseType",
                [        ]],["BooleanType","Thelia\/Type\/BooleanType.html"," < BaseType",
                [        ]],["EnumListType","Thelia\/Type\/EnumListType.html"," < BaseType",
                [        ]],["EnumType","Thelia\/Type\/EnumType.html"," < BaseType",
                [        ]],["FloatToFloatArrayType","Thelia\/Type\/FloatToFloatArrayType.html"," < BaseType",
                [        ]],["FloatType","Thelia\/Type\/FloatType.html"," < BaseType",
                [        ]],["IntListType","Thelia\/Type\/IntListType.html"," < BaseType",
                [        ]],["IntToCombinedIntsListType","Thelia\/Type\/IntToCombinedIntsListType.html"," < BaseType",
                [        ]],["IntToCombinedStringsListType","Thelia\/Type\/IntToCombinedStringsListType.html"," < BaseType",
                [        ]],["IntType","Thelia\/Type\/IntType.html"," < BaseType",
                [        ]],["JsonType","Thelia\/Type\/JsonType.html"," < BaseType",
                [        ]],["ModelType","Thelia\/Type\/ModelType.html"," < BaseType",
                [        ]],["ModelValidIdType","Thelia\/Type\/ModelValidIdType.html"," < BaseType",
                [        ]]        ]]        ]]        ]

